### ISSUE TITLE
Add documentation on readthedocs

### ISSUE THREAD

**Issue by pradal** [openalea-incubator/strawberry#5]
Write the documentation and build it with readthedocs

**Comment by mlabadie** [comment]
The documentation on readthedoc is set up. 
However, some functionalities and documentation are still missing, such as the description of functions, the implementation of statistical analysis functions

**Comment by pomme-abricot** [comment]
Tutorials notebooks have been added to the example/tutorials folder. 
They also are included in the documentation.

**Comment by pomme-abricot** [comment]
Doc compiles
